# Generated by Django 5.0.3 on 2024-03-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='DSA Bootcamp', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Indore', max_length=50),
        ),
    ]
